plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mk15.portinspector'
    compileSdk 34

    defaultConfig {
        applicationId 'com.mk15.portinspector'
        minSdk 23
        targetSdk 28
        versionCode 56
        versionName '1.5.6'
    }

    sourceSets {
        main {
            jniLibs.srcDirs = [rootProject.file('.native-jniLibs')]
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
